version: '3.8'
services:
  usuarios-1:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SERVER_PORT=8081
    ports:
      - "8081:8081"
    restart: always

  usuarios-2:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SERVER_PORT=8082
    ports:
      - "8082:8082"
    restart: always
    
networks:
  default:
    driver: bridge
