version: '3.8'
services:
  reservas-1:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - SERVER_PORT=8083
    ports:
      - "8083:8083"
    restart: always

  reservas-2:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - SERVER_PORT=8084
    ports:
      - "8084:8084"
    restart: always

networks:
  default:
    driver: bridge
